apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-app
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/ch007m/my-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true